### ISSUE TITLE
cannot import name 'SparseModule' from 'mmcv.ops'

### ISSUE THREAD

**Issue by zjw102** [atonderski/lidarclip#1]
cannot import name 'SparseModule' from 'mmcv.ops' how to deal this

**Comment by georghess** [comment]
Is then when running the [provided dockerfile](https://github.com/atonderski/lidarclip/blob/main/docker/Dockerfile)?

**Comment by zjw102** [comment]
no, when i running python train.py.My teacher told me that docker was too much trouble, so instead of using docker, I wanted to run the code directly. You can tell me the environment you run, such as mmcv torch CUDA.Thanks

**Comment by atonderski** [comment]
In that case, I recommend you follow the installation steps in the dockerfile (where exact versions are specified). You can execute the commands in your preferred environment instead.

**Comment by JayKarhade** [comment]
I get the same error when using the provided DockerFile, any quick fixes? Thank you!

**Comment by georghess** [comment]
Just double-checking, you are not getting any errors when installing mmcv when building the container?

**Comment by JayKarhade** [comment]
Hi @georghess thanks for responding quickly!

Yes that's right. The line that gives the error is : 

from mmdet3d.models import build_model

with the following error message

  File "/sst/mmdet3d/ops/sparse_block.py", line 9, in <module>
    from mmcv.ops import SparseModule, SparseSequential
ImportError: cannot import name 'SparseModule' from 'mmcv.ops' (/opt/conda/lib/python3.8/site-packages/mmcv/ops/__init__.py)
I also faced some other errors with respect to numpy and cv2. Particularly, i got an 

> 
attributeerror: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_gstreamerpipeline' (most likely due to a circular import)

which i resolved by RUN pip install opencv-python==4.5.5.64

Also the RUN pip install --upgrade numpy seems to give numpy version errors in pip's dependency resolver.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nuscenes-devkit 1.1.10 requires pycocotools>=2.0.1, which is not installed.
mmdet3d 0.15.0 requires numpy<1.20.0, but you have numpy 1.24.4 which is incompatible.

**Comment by JayKarhade** [comment]
Hey @georghess , maybe you could upload your working docker image to docker hub and provide a link for users to pull the image?

**Comment by georghess** [comment]
Hi @JayKarhade,
Unfortunately, I don't have a working docker image anymore, as we are using singularity on our cluster. But I'll set up a new docker container now to try to reproduce the error and get back to you later.

**Comment by georghess** [comment]
Hi @JayKarhade,

I've updated the docker file and instructions in the readme. I got everything up and running from a clean slate using them, so please try them out and let me know if you run into any issues.

One problem I've encountered when running mixed precision is [this](https://github.com/tusen-ai/SST/blob/8b795c40632c3868b091dc032fff7099c0d21bc5/mmdet3d/ops/norm.py#L56) throwing an error. One workaround is to change [this line](https://github.com/tusen-ai/SST/blob/8b795c40632c3868b091dc032fff7099c0d21bc5/mmdet3d/models/voxel_encoders/utils.py#L129)
to 
`@auto_fp16(apply_to=('inputs'), out_fp32=False)`

and [this line](https://github.com/tusen-ai/SST/blob/8b795c40632c3868b091dc032fff7099c0d21bc5/mmdet3d/models/voxel_encoders/utils.py#L142) to 
`x = self.norm(x.float())`
