### ISSUE TITLE
Reason for converting point clouds into KITTI coordinate

### ISSUE THREAD

**Issue by dahjungc** [atonderski/lidarclip#5]
Hello 
I am trying to finetune lidarclip with my own dataset. When I was implementing data loader for my dataset, I found a question from your implementation. 

In loader.py (line below), you convert the point clouds in Camera coordinates to KITTI coordinate. 
https://github.com/atonderski/lidarclip/blob/2b781bf41ef397289704c01ccdca2c8af1228531/lidarclip/loader.py#L349

Could you provide the reason or explanation for this coordinate conversion ? Wouldn't we loose the alignment between image and point cloud by changing coordinate system?

Thank you!

**Comment by georghess** [comment]
Hi, 

We switch from the camera coordinates system (x - right, y - down, z - forward) to KITTI (x - forward, y - left, z - up) because the SST encoder expects the z axis to point upward.

I'm not sure if I understand the question about alignment. We do not move the point cloud in any way, we simply switch around the axes.

**Comment by dahjungc** [comment]
Hello @georghess  Thanks for the reply. I am also wondering that if there  is any reason for converting points to camera coordinate instead of lidar coordinate ? 
Can I use my points as is (in lidar coordinate without lidar2cam projection) assuming my point clouds are already reduced within image frame (like you do in the loader) ?

**Comment by atonderski** [comment]
As long as you are consistent you can use whichever coordinate frame you want :) As georg said, we use the KITTI coordinate system because the lidar encoder has hardcoded assumptions on the meaning of the z axis. So as long as your native lidar coordinate follows this I believe there should be no issue.

**Comment by dahjungc** [comment]
Thanks @atonderski  for your reply. My lidar coordinate already has z axis up and I have reduced points saved. I will try to use points in lidar coordinate. Thank you all for answers!!
